"""Add message field to whatsapp_broadcasts

Revision ID: 0a63c2698d38
Revises: b77903db036e
Create Date: 2026-09-21 10:42:43.920889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a63c2698d38'
down_revision = 'b77903db036e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills any existing broadcast rows (their real
    # message text was never stored -- only the truncated title was) so the
    # NOT NULL constraint doesn't fail against them.
    with op.batch_alter_table('whatsapp_broadcasts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.Text(), nullable=False, server_default=''))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whatsapp_broadcasts', schema=None) as batch_op:
        batch_op.drop_column('message')

    # ### end Alembic commands ###
