"""Add role_permissions table

Revision ID: 5167124fb514
Revises: f55cfb519297
Create Date: 2026-09-15 08:45:36.587790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5167124fb514'
down_revision = 'f55cfb519297'
branch_labels = None
depends_on = None


role_permissions_table = sa.table(
    "role_permissions",
    sa.column("role", sa.String),
    sa.column("resources", sa.JSON),
)

# Same starting point as DEFAULT_RESOURCE_ACCESS in app/utils/decorators.py --
# seeded here so a fresh deploy has real rows from day one instead of relying
# only on the in-code fallback.
SEED_RESOURCES = {
    "comms": [
        "contacts", "stories", "gallery", "impact", "newsletter",
        "whatsapp_inbox", "whatsapp_broadcast", "whatsapp_assistant",
    ],
    "programs": ["contacts", "events", "registrations", "applications"],
    "mel": ["donations", "impact", "reports"],
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('resources', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    # ### end Alembic commands ###

    op.bulk_insert(
        role_permissions_table,
        [{"role": role, "resources": resources} for role, resources in SEED_RESOURCES.items()],
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_permissions')
    # ### end Alembic commands ###
