"""Add partners table

Revision ID: b77903db036e
Revises: 5167124fb514
Create Date: 2026-09-18 11:07:24.947668

"""
from datetime import datetime, timezone

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b77903db036e'
down_revision = '5167124fb514'
branch_labels = None
depends_on = None

partners_table = sa.table(
    "partners",
    sa.column("name", sa.String),
    sa.column("category", sa.String),
    sa.column("created_at", sa.DateTime),
)

role_permissions_table = sa.table(
    "role_permissions",
    sa.column("id", sa.Integer),
    sa.column("role", sa.String),
    sa.column("resources", sa.JSON),
)

# Same four partners PartnerContext.jsx (the localStorage-only version this
# replaces) shipped as defaults, so moving to a real backend doesn't blank
# out what's already on the live site.
SEED_PARTNERS = [
    {"name": "SEMA", "category": "Civic technology"},
    {"name": "Strategic Applications", "category": "International"},
    {"name": "Creatives Garage", "category": "Creative hub"},
    {"name": "YWCA", "category": "Community"},
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('public_id', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    now = datetime.now(timezone.utc)
    op.bulk_insert(
        partners_table,
        [{"created_at": now, **p} for p in SEED_PARTNERS],
    )

    # "partners" is a new resource -- fold it into whatever Programs already
    # has saved, rather than overwriting a role that may have been
    # customised since the previous migration. Uses the mapped JSON column
    # (via the table construct) rather than raw SQL so it deserializes the
    # same way on SQLite (dev) and Postgres (prod).
    conn = op.get_bind()
    row = conn.execute(
        sa.select(role_permissions_table.c.id, role_permissions_table.c.resources)
        .where(role_permissions_table.c.role == "programs")
    ).fetchone()
    if row is not None:
        row_id, resources = row
        resources = resources or []
        if "partners" not in resources:
            conn.execute(
                role_permissions_table.update()
                .where(role_permissions_table.c.id == row_id)
                .values(resources=resources + ["partners"])
            )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('partners')
    # ### end Alembic commands ###
